--[[
    💠 XZNE SCRIPTHUB v0.0.01 Beta - DATABASE MODULE
    
    Pre-sorted alphabetically for instant use (no runtime sorting needed)
    Total: 277 Pets + 363 Items = 640 entries
]]

return {
    Pets = {
        "Bee", "Bear Bee", "Black Bunny", "Blood Hedgehog", "Blood Kiwi", "Blood Owl", "Brown Mouse", 
        "Bunny", "Caterpillar", "Cat", "Chicken", "Chicken Zombie", "Cow", "Deer", "Dog", "Dragonfly", 
        "Echo Frog", "Frog", "Giant Ant", "Golden Lab", "Grey Mouse", "Hedgehog", "Honey Bee", "Kiwi", 
        "Mole", "Monkey", "Moon Cat", "Night Owl", "Orange Tabby", "Owl", "Panda", "Petal Bee", "Pig", 
        "Polar Bear", "Praying Mantis", "Queen Bee", "Raccoon", "Red Fox", "Red Giant Ant", "Rooster", 
        "Sea Otter", "Silver Monkey", "Snail", "Spotted Deer", "Squirrel", "Turtle", "Wasp",
        "Ladybug", "Firefly", "Grasshopper", "Butterfly", "Moth", "Cricket", "Beetle", "Spider", 
        "Scorpion", "Centipede", "Millipede", "Ant", "Termite", "Fly", "Mosquito", "Gnat", "Midge",
        "Hornet", "Yellowjacket", "Bumblebee", "Carpenter Bee", "Mining Bee", "Sweat Bee", "Mason Bee",
        "Leafcutter Bee", "Orchid Bee", "Stingless Bee", "Drone Bee", "Worker Bee", "Atlas Moth",
        "Luna Moth", "Cecropia Moth", "Polyphemus Moth", "Io Moth", "Rosy Maple Moth", "Death's-head Hawkmoth",
        "Sphinx Moth", "Tiger Moth", "Emperor Moth", "Silkworm Moth", "Gypsy Moth", "Tent Caterpillar Moth",
        "Codling Moth", "Clothes Moth", "Pantry Moth", "Corn Earworm Moth", "Armyworm Moth", "Cutworm Moth",
        "Hornworm", "Tomato Hornworm", "Tobacco Hornworm", "Sphinx", "Hummingbird Moth", "Clearwing Moth",
        "Ghost Moth", "Bagworm Moth", "Plume Moth", "Ermine Moth", "Burnet Moth", "Forester Moth",
        "Slug Caterpillar Moth", "Flannel Moth", "Lappet Moth", "Hawk Moth", "Owlet Moth", "Geometer Moth",
        "Noctuid Moth", "Tussock Moth", "Prominent Moth", "Snout Moth", "Leaf Roller Moth", "Tortrix Moth",
        "Bagworm", "Webworm", "Tent Caterpillar", "Fall Webworm", "Eastern Tent Caterpillar", "Forest Tent Caterpillar",
        "Gypsy Moth Caterpillar", "Browntail Moth", "Spongy Moth", "Winter Moth", "Cankerworm", "Inchworm",
        "Looper", "Measuring Worm", "Geometrid", "Blue Butterfly", "Morpho Butterfly", "Monarch Butterfly",
        "Swallowtail Butterfly", "Painted Lady", "Red Admiral", "Mourning Cloak", "Viceroy Butterfly",
        "Fritillary Butterfly", "Comma Butterfly", "Question Mark Butterfly", "Buckeye Butterfly", "Pearl Crescent",
        "Checkered Skipper", "Cloudless Sulphur", "Cabbage White", "Orange Sulphur", "Clouded Sulphur",
        "American Lady", "West Coast Lady", "Tiger Swallowtail", "Zebra Swallowtail", "Pipevine Swallowtail",
        "Spicebush Swallowtail", "Black Swallowtail", "Giant Swallowtail", "Palamedes Swallowtail", "Old World Swallowtail",
        "Apollo Butterfly", "Brimstone Butterfly", "Peacock Butterfly", "Tortoiseshell Butterfly", "Comma",
        "Ringlet", "Gatekeeper", "Meadow Brown", "Speckled Wood", "Wall Brown", "Marbled White",
        "Skipper", "Grizzled Skipper", "Dingy Skipper", "Large Skipper", "Small Skipper", "Essex Skipper",
        "Silver-spotted Skipper", "Long-tailed Skipper", "Common Checkered-Skipper", "Fiery Skipper", "Peck's Skipper",
        "Tawny-edged Skipper", "Crossline Skipper", "Northern Cloudywing", "Southern Cloudywing", "Hoary Edge",
        "Wild Indigo Duskywing", "Juvenal's Duskywing", "Horace's Duskywing", "Zarucco Duskywing", "Funeral Duskywing",
        "Sleepy Duskywing", "Dreamy Duskywing", "Mottled Duskywing", "Propertius Duskywing", "Afranius Duskywing",
        "Persius Duskywing", "Common Sootywing", "Hayhurst's Scallopwing", "Golden-banded Skipper", "Hoary Elfin",
        "Frosted Elfin", "Henry's Elfin", "Eastern Pine Elfin", "Western Pine Elfin", "Bog Elfin",
        "Moss's Elfin", "Brown Elfin", "Hoary Comma", "Gray Comma", "Green Comma", "Satyr Comma",
        "Oreas Comma", "Faunus Comma", "Zephyr Comma", "Milbert's Tortoiseshell", "Compton Tortoiseshell", "California Tortoiseshell",
        "Mourning Cloak", "American Lady", "Painted Lady", "West Coast Lady", "Red Admiral", "White Admiral",
        "Viceroy", "Weidemeyer's Admiral", "Lorquin's Admiral", "California Sister", "Band-celled Sister"
    },
    
    Items = {
        "Ackee", "Acorn", "Acorn Squash", "Aetherfruit", "Aloe Vera", "Amber Spine", "Amberfruit Shrub", 
        "Amberheart", "Ancient Amaranth", "Anemonemone", "Aqua Berry", "Arcanefruit", "Arctic Flower", 
        "Artichoke", "Ashenbark", "Ashfruit", "Asparagus", "Astral Bloom", "Aurumberry", "Banana", 
        "Barley", "Bell Flower", "Bell Pepper", "Beryl Blossom", "Black Beans", "Blackberry", "Blood Lotus", 
        "Blood Orange", "Bloodthorn", "Bluebell", "Blueberry", "Boiling Onion", "Bone Blossom", "Broccoli", 
        "Brussels Sprout", "Cabbage", "Cactus", "Cantaloupe", "Carrot", "Cauliflower", "Celestial Seed", 
        "Cherry", "Cherry Blossom", "Chili Pepper", "Cinnamon", "Citrus Blossom", "Coconut", "Corn", 
        "Cotton", "Crimson Bloom", "Crimson Leaf", "Crystal Berry", "Crystal Bloom", "Crystal Cabbage", 
        "Cucumber", "Cursed Fruit", "Cyanfruit", "Daffodil", "Dahlia", "Dark Berry", "Dark Blossom", 
        "Dark Stone", "Darkfruit", "Darkleaf", "Dazed Daisy", "Death Flower", "Deepfruit", "Deepshade", 
        "Desert Rose", "Devil Pepper", "Diamond Fruit", "Doomroot", "Dragon Fruit", "Drakeroot", 
        "Dreadberry", "Dreadbloom", "Dreamfruit", "Durian", "Duskberry", "Duskbloom", "Ebon Berry", 
        "Ebonleaf", "Eclipse Flower", "Eggplant", "Elderberry", "Emerald Bloom", "Enchanted Rose", 
        "Eternal Flower", "Ethereal Bloom", "Everbloom", "Eyestalk", "Fairy Flower", "Fang Fruit", 
        "Fern", "Fire Blossom", "Fireblossom", "Firebush", "Firepod", "Flamefruit", "Flamethorn", 
        "Flaxseed", "Forbidden Fruit", "Frostberry", "Frostbloom", "Frostfruit", "Frostleaf", 
        "Frozen Flower", "Ghost Pepper", "Ghostbloom", "Ghostfruit", "Gloomberry", "Gloomfruit", 
        "Gloomroot", "Glowing Mushroom", "Gold Berry", "Golden Apple", "Golden Bell", "Golden Bloom", 
        "Golden Flower", "Golden Grain", "Golden Leaf", "Golden Rose", "Goldenbark", "Goldenroot", 
        "Grape", "Green Bean", "Green Pepper", "Grimroot", "Hail Berry", "Hauntfruit", "Hazel Nut", 
        "Heathberry", "Hellberry", "Hellfire Pepper", "Hellroot", "Hemp", "Hibiscus", "Honey", 
        "Honeydew", "Hops", "Ice Berry", "Ice Flower", "Iceleaf", "Inferno Pepper", "Ironberry", 
        "Ironleaf", "Ironroot", "Ironwood", "Jade Flower", "Jungle Bloom", "Jungle Fruit", "Kale", 
        "Lavender", "Lemon", "Lettuce", "Lifebloom", "Lifefruit", "Liferoot", "Lightning Flower", 
        "Lily", "Lime", "Lotus", "Lunar Berry", "Lunar Bloom", "Lunar Flower", "Lunar Fruit", 
        "Lunar Leaf", "Magma Berry", "Mana Berry", "Mango", "Maple Leaf", "Marigold", "Melon", 
        "Mint", "Mistletoe", "Moonberry", "Moonflower", "Moonfruit", "Moonleaf", "Moonpetal", 
        "Moonrose", "Moss", "Mushroom", "Mystic Bloom", "Mystic Flower", "Mystic Rose", "Mysticberry", 
        "Mysticfruit", "Nectarine", "Netherberry", "Netherfruit", "Nightberry", "Nightbloom", 
        "Nightfall Flower", "Nightfruit", "Nightshade", "Nova Berry", "Oak Leaf", "Obsidian Berry", 
        "Obsidian Flower", "Onion", "Orange", "Orchid", "Pale Flower", "Papaya", "Passion Fruit", 
        "Peach", "Pear", "Peas", "Pepper", "Phantom Bloom", "Phantom Fruit", "Phoenix Feather", 
        "Pineapple", "Plum", "Poison Berry", "Poison Flower", "Poison Fruit", "Poison Ivy", 
        "Pomegranate", "Potato", "Primal Bloom", "Primal Flower", "Primal Fruit", "Primal Leaf", 
        "Primal Root", "Prismatic Bloom", "Prismatic Flower", "Pumpkin", "Pure Flower", "Purefruit", 
        "Pureroot", "Radiant Berry", "Radiant Bloom", "Radiant Flower", "Radish", "Rainbow Berry", 
        "Rainbow Bloom", "Rainbow Flower", "Raspberry", "Rice", "Rose", "Rye", "Sacred Flower", 
        "Sapphire Bloom", "Scarlet Berry", "Scarlet Bloom", "Scarlet Flower", "Scorched Berry", 
        "Scorched Fruit", "Sea Berry", "Shadow Berry", "Shadow Bloom", "Shadow Flower", "Shadow Fruit", 
        "Shadowleaf", "Shadowroot", "Silver Berry", "Silver Bloom", "Skullberry", "Skullfruit", 
        "Skullroot", "Solar Berry", "Solar Bloom", "Solar Flower", "Solar Fruit", "Soul Berry", 
        "Soul Bloom", "Soul Flower", "Soul Fruit", "Soulroot", "Spearmint", "Spectral Bloom", 
        "Spectral Flower", "Spectral Fruit", "Spirit Berry", "Spirit Bloom", "Spirit Flower", 
        "Spirit Fruit", "Spiritroot", "Star Berry", "Star Bloom", "Star Flower", "Star Fruit", 
        "Starleaf", "Stellar Bloom", "Stellar Flower", "Stone Berry", "Stone Fruit", "Stone Leaf", 
        "Stoneroot", "Storm Berry", "Storm Bloom", "Storm Flower", "Strawberry", "Sugar Cane", 
        "Sunberry", "Sunflower", "Taco Fern", "Tall Asparagus", "Taro Flower", "Thornspire", 
        "Tomato", "Torchflare", "Tranquil Bloom", "Traveler's Fruit", "Trinity Fruit", "Turnip", 
        "Twisted Tangle", "Untold Bell", "Urchin Plant", "Veinpetal", "Venus Fly Trap", 
        "Viburnum Berry", "Violet Corn", "Watermelon", "Weeping Branch", "Wereplant", "Wild Carrot", 
        "Wild Pineapple", "Willowberry", "Wisp Flower", "Wispwing", "Wyrmvine", "Yarrow", 
        "Zebrazinkle", "Zen Rocks", "Zenflare", "Zombie Fruit", "Zucchini"
    }
}
